[package]
name = "merkle-tree-stream"
description = "A stream that generates a merkle tree based on the incoming data."
version = "0.3.0"
repository = "https://github.com/datrs/merkle-tree-stream"
documentation = "https://docs.rs/merkle-tree-stream"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
flat-tree = "3.3.0"

[dev-dependencies]
clippy = "0.0"
rust_sodium = "0.7.0"
